language: swift

jobs:
  include:
    - osx_image: xcode10.1
      if: branch != swift3
    - osx_image: xcode8 # <https://github.com/hkgumbs/multi/issues/1>
      if: branch == swift3

script:
  - swift build $SWIFT_FLAGS

notifications:
  email: false
